apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-pipeline-app
  labels:
    app: cicd-pipeline-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: cicd-pipeline-app
  template:
    metadata:
      labels:
        app: cicd-pipeline-app
    spec:
      containers:
        - name: cicd-pipeline-node
          image: poojadevops1012/cicd-pipeline-node:v10
          ports:
            - containerPort: 8080

