apiVersion: v1
kind: Service
metadata:
  name: cicd-pipeline-app
  labels:
    app: cicd-pipeline-app
spec:
  selector:
    app: cicd-pipeline-app
  ports:
    - name: cicd-pipeline-node
      protocol: TCP
      port: 4001
      targetPort: 80
  type: LoadBalancer
